// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYj3GsivZSza2f4ou2hPpC026PgVCsEw',
    appId: '1:557994569761:web:0f0d20ff4a571a197bb360',
    messagingSenderId: '557994569761',
    projectId: 'remotcoba-6efcf',
    authDomain: 'remotcoba-6efcf.firebaseapp.com',
    storageBucket: 'remotcoba-6efcf.firebasestorage.app',
    measurementId: 'G-VTLHQX4RED',
    databaseURL:
        'https://remotcoba-6efcf-default-rtdb.firebaseio.com/', // Menambahkan databaseURL
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRecdW3pb57ma_89UvYlmOU_yxhRhtCg',
    appId: '1:557994569761:android:e8bd3ad5666e784a7bb360',
    messagingSenderId: '557994569761',
    projectId: 'remotcoba-6efcf',
    storageBucket: 'remotcoba-6efcf.firebasestorage.app',
    databaseURL:
        'https://remotcoba-6efcf-default-rtdb.firebaseio.com/', // Menambahkan databaseURL
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIJ7BZCUqjq_kbRXSpWFQNGXbm_2y1W0I',
    appId: '1:557994569761:ios:1d57d3d9fdad0bfa7bb360',
    messagingSenderId: '557994569761',
    projectId: 'remotcoba-6efcf',
    storageBucket: 'remotcoba-6efcf.firebasestorage.app',
    iosBundleId: 'com.example.remotkontrol',
    databaseURL:
        'https://remotcoba-6efcf-default-rtdb.firebaseio.com/', // Menambahkan databaseURL
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIJ7BZCUqjq_kbRXSpWFQNGXbm_2y1W0I',
    appId: '1:557994569761:ios:1d57d3d9fdad0bfa7bb360',
    messagingSenderId: '557994569761',
    projectId: 'remotcoba-6efcf',
    storageBucket: 'remotcoba-6efcf.firebasestorage.app',
    iosBundleId: 'com.example.remotkontrol',
    databaseURL:
        'https://remotcoba-6efcf-default-rtdb.firebaseio.com/', // Menambahkan databaseURL
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzYj3GsivZSza2f4ou2hPpC026PgVCsEw',
    appId: '1:557994569761:web:0c782c37587f24367bb360',
    messagingSenderId: '557994569761',
    projectId: 'remotcoba-6efcf',
    authDomain: 'remotcoba-6efcf.firebaseapp.com',
    storageBucket: 'remotcoba-6efcf.firebasestorage.app',
    measurementId: 'G-0RZHY4GS22',
    databaseURL:
        'https://remotcoba-6efcf-default-rtdb.firebaseio.com/', // Menambahkan databaseURL
  );
}
